name: football_premier_league
description: "footballPremierLeague"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #dart
  meta: ^1.4.0
  quiver: ^3.2.1
  equatable: ^2.0.5

  dio: ^5.4.3               # HTTP 요청을 위한 Dio
  freezed_annotation: ^2.4.4  # 불변 모델 생성을 위한 Freezed
  json_annotation: ^4.9.0   # JSON 파싱을 위한 json_annotation
  flutter_riverpod: ^2.5.1  # 상태 관리를 위한 Riverpod
  riverpod_annotation: ^2.3.5  # 상태 관리를 위한 Riverpod
  hooks_riverpod: ^2.5.1     # Hook을 사용하기 위한 hooks_riverpod
  go_router: ^14.2.3        # 라우팅을 위한 GoRouter
  flutter_hooks: ^0.18.0    # Hook을 사용하기 위한 flutter_hooks
  shared_preferences: ^2.2.3  # 로컬 저장소를 위한 shared_preferences
  cupertino_icons: ^1.0.6  # 아이콘을 위한 cupertino_icons
  animations: ^2.0.11    # 애니메이션을 위한 animations
  cached_network_image: ^3.2.3  # 이미지 캐싱을 위한 cached_network_image
  flutter_svg: ^2.0.3   # SVG 이미지를 위한 flutter_svg
  transparent_image: ^2.0.1 # 이미지 투명도를 위한 transparent_image
  dropdown_button2: ^2.3.9 # 드롭다운 버튼을 위한 dropdown_button2
  table_calendar: ^3.1.2 # 달력을 위한 table_calendar
  data_table_2: ^2.5.15 # 데이터 테이블을 위한 data_table_2
  appbar_animated: ^0.0.3 # 애니메이션 앱바를 위한 appbar_animated
  background_app_bar: ^2.1.0 # 배경 앱바를 위한 background_app_bar
  draggable_home: ^1.0.5  # 드래그 가능한 홈을 위한 draggable_home
  sliver_snap: ^1.2.0 # 슬리버 스냅을 위한 sliver_snap

  #util
  velocity_x: ^4.1.0  # UI를 위한 velocity_x
  eva_icons_flutter: ^3.1.0 # 아이콘을 위한 eva_icons_flutter
  google_fonts: ^4.0.4  # 구글 폰트를 위한 google_fonts
  easy_localization: ^3.0.2 # 다국어 지원을 위한 easy_localization
  flutter_cache_manager: ^3.3.0 # 캐시 관리를 위한 flutter_cache_manager
  keyboard_utils_fork: ^0.0.4 # 키보드 관리를 위한 keyboard_utils_fork
  envied: ^0.5.4+1  # 환경 변수를 위한 envied
  logger: ^2.4.0  # 로그를 위한 logger
  path_provider: ^2.1.4  # 파일 경로를 위한 path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # 앱 아이콘을 위한 flutter_launcher_icons
  flutter_lints: ^4.0.0 # Lint를 위한 flutter_lints
  build_runner: ^2.4.12  # 빌드를 위한 build_runner
  riverpod_generator: ^2.4.0 # 상태 관리를 위한 riverpod_generator
  freezed: ^2.5.7 # 불변 모델 생성을 위한 freezed
  json_serializable: ^6.8.0  # JSON 파싱을 위한 json_serializable
  envied_generator: ^0.5.4+1  # 환경 변수를 위한 envied_generator
  analyzer: ^6.7.0

flutter_launcher_icons:
  #  android: "launcher_icon"
  #  ios: "AppIcon"
  android: true
  ios: true
  image_path_ios: "assets/icon/app_icon.png"
  image_path_android: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icon/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300

